-- =============================================================================
-- دَورلي — Agency CRM columns, workspace RLS for leads, listing view events
-- Run in Supabase SQL Editor once (safe to re-run: IF NOT EXISTS / DROP POLICY)
-- =============================================================================

-- ─── Leads: CRM status + notes (agency workspace) ───────────────────────────
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS crm_status text NOT NULL DEFAULT 'new';

ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS agency_notes text;

ALTER TABLE public.leads DROP CONSTRAINT IF EXISTS leads_crm_status_check;
ALTER TABLE public.leads
  ADD CONSTRAINT leads_crm_status_check
  CHECK (crm_status IN ('new', 'contacted', 'closed'));

COMMENT ON COLUMN public.leads.crm_status IS 'Agency CRM pipeline: new | contacted | closed';
COMMENT ON COLUMN public.leads.agency_notes IS 'Private notes visible to agency owner only';

-- ─── Leads: agency owner can read/update leads on listings under their agency
DROP POLICY IF EXISTS "leads_select_agency_workspace" ON public.leads;
CREATE POLICY "leads_select_agency_workspace"
  ON public.leads FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.properties p
      INNER JOIN public.agencies a ON a.id = p.agency_id AND a.owner_id = auth.uid()
      WHERE p.id = leads.property_id
    )
  );

DROP POLICY IF EXISTS "leads_update_agency_workspace" ON public.leads;
CREATE POLICY "leads_update_agency_workspace"
  ON public.leads FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.properties p
      INNER JOIN public.agencies a ON a.id = p.agency_id AND a.owner_id = auth.uid()
      WHERE p.id = leads.property_id
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.properties p
      INNER JOIN public.agencies a ON a.id = p.agency_id AND a.owner_id = auth.uid()
      WHERE p.id = leads.property_id
    )
  );

-- ─── Anonymous/authenticated page views (active listings only) ────────────
CREATE TABLE IF NOT EXISTS public.property_listing_view_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id bigint NOT NULL REFERENCES public.properties (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_plve_property_created
  ON public.property_listing_view_events (property_id, created_at DESC);

ALTER TABLE public.property_listing_view_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "plve_insert_public" ON public.property_listing_view_events;
CREATE POLICY "plve_insert_public"
  ON public.property_listing_view_events FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.properties p
      WHERE p.id = property_id AND p.status = 'active'
    )
  );

DROP POLICY IF EXISTS "plve_select_agency_owner" ON public.property_listing_view_events;
CREATE POLICY "plve_select_agency_owner"
  ON public.property_listing_view_events FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.properties p
      INNER JOIN public.agencies a ON a.id = p.agency_id AND a.owner_id = auth.uid()
      WHERE p.id = property_listing_view_events.property_id
    )
  );

COMMENT ON TABLE public.property_listing_view_events IS 'Fire-and-forget listing detail views for agency analytics';

-- ─── Security model (RLS review) ───────────────────────────────────────────
-- Leads SELECT/UPDATE (`leads_*_agency_workspace`): only rows whose `property_id`
-- belongs to a property where `properties.agency_id = agencies.id` AND
-- `agencies.owner_id = auth.uid()`. Other agencies' listings never satisfy the join.
-- View events SELECT (`plve_select_agency_owner`): same join on `property_id`.
-- View INSERT (`plve_insert_public`): any anon/authenticated client may insert only
-- when the target `property_id` exists and `properties.status = 'active'` (anti-spam
-- to dead ids; does not expose other agencies' rows via SELECT).
-- Property owners may still have separate policies (e.g. `leads_select_property_owner`);
-- those are additive (OR) with workspace policies for SELECT on leads.
